---

- name: Test for podman command
  shell: command -v podman
  register: have_podman_raw
  ignore_errors: yes

- name: Set have_podman
  set_fact:
    have_podman: "{{ have_podman_raw.rc == 0 }}"

- name: Fail if podman command not found
  fail:
    msg: "Podman command not found"
  ignore_errors: true
  when: not have_podman