---


- name: Check for Postgres docker image presence
  shell: docker images | grep postgres | grep "{{ POSTGRES_VERSION }}"
  become: true
  register: postgres_docker_image_raw
  ignore_errors: yes

- name: Set Postgres docker image presence to false
  set_fact:
    postgres_docker_image_present: false
  when:
    - postgres_docker_image_raw.rc != 0

- name: Set Postgres docker image presence to true if output is not empty
  set_fact:
    postgres_docker_image_present: "{{ postgres_docker_image_raw['stdout_lines']|length > 0 }}"
  when:
    - postgres_docker_image_raw.rc == 0
    - "'stdout_lines' in postgres_docker_image_raw"

- name: Default that docker load was not attempted for Postgres
  set_fact:
    load_docker_postgres_attempted: false

- name: Docker load was attempted for Postgres
  set_fact:
    load_docker_postgres_attempted: true
  when:
    - not postgres_docker_image_present
    - find_postgres_image_local.stat.exists == true

- name: Load Postgres image into local Docker registry
  shell: docker load -i "{{postgres_image_local_path}}"
  become: true
  when:
    - not postgres_docker_image_present
    - find_postgres_image_local.stat.exists == true

- name: Check for Postgres docker image presence
  shell: docker images | grep postgres | grep "{{ POSTGRES_VERSION }}"
  become: true
  register: postgres_docker_image_raw
  ignore_errors: yes
  when:
    load_docker_postgres_attempted|bool

- name: Set Postgres docker image presence to false
  set_fact:
    postgres_docker_image_present: false
  when:
    - load_docker_postgres_attempted|bool
    - postgres_docker_image_raw.rc != 0

- name: Set Postgres docker image presence to true if output is not empty
  set_fact:
    postgres_docker_image_present: "{{ postgres_docker_image_raw['stdout_lines']|length > 0 }}"
  when:
    - load_docker_postgres_attempted|bool
    - postgres_docker_image_raw.rc == 0
    - "'stdout_lines' in postgres_docker_image_raw"

- name: Make sure Postgres docker image loaded (it successfully loaded if skipped)
  fail:
    msg: "The Postgres DB's docker image was not found in the output of the docker images command."
  when:
    - load_docker_postgres_attempted|bool
    - not postgres_docker_image_present

