---


- name: Check for Postgres {{ container_command }} image presence
  shell: "{{ container_command }} images | grep postgres | grep {{ POSTGRES_VERSION }}"
  become: true
  register: postgres_docker_image_raw
  ignore_errors: yes

- name: Set Postgres {{ container_command }} image presence to false
  set_fact:
    postgres_docker_image_present: false
  when:
    - postgres_docker_image_raw.rc != 0

- name: Set Postgres {{ container_command }} image presence to true if output is not empty
  set_fact:
    postgres_docker_image_present: "{{ postgres_docker_image_raw['stdout_lines']|length > 0 }}"
  when:
    - postgres_docker_image_raw.rc == 0
    - "'stdout_lines' in postgres_docker_image_raw"

- name: Default that {{ container_command }} load was not attempted for Postgres
  set_fact:
    load_docker_postgres_attempted: false

- name: "{{ container_command }} load was attempted for Postgres"
  set_fact:
    load_docker_postgres_attempted: true
  when:
    - not postgres_docker_image_present
    - find_postgres_image_local.stat.exists == true

- name: Load Postgres image into local {{ container_command }} registry
  shell: "{{ container_command }} load -i {{postgres_image_local_path}}"
  become: true
  when:
    - not postgres_docker_image_present
    - find_postgres_image_local.stat.exists == true

- name: Check for Postgres {{ container_command }} image presence
  shell: "{{ container_command }} images | grep postgres | grep {{ POSTGRES_VERSION }}"
  become: true
  register: postgres_docker_image_raw
  ignore_errors: yes
  when:
    load_docker_postgres_attempted|bool

- name: Set Postgres {{ container_command }} image presence to false
  set_fact:
    postgres_docker_image_present: false
  when:
    - load_docker_postgres_attempted|bool
    - postgres_docker_image_raw.rc != 0

- name: Set Postgres {{ container_command }} image presence to true if output is not empty
  set_fact:
    postgres_docker_image_present: "{{ postgres_docker_image_raw['stdout_lines']|length > 0 }}"
  when:
    - load_docker_postgres_attempted|bool
    - postgres_docker_image_raw.rc == 0
    - "'stdout_lines' in postgres_docker_image_raw"

- name: Make sure Postgres {{ container_command }} image loaded (it successfully loaded if skipped)
  fail:
    msg: "The Postgres DB's {{ container_command }} image was not found in the output of the {{ container_command }} images command."
  when:
    - load_docker_postgres_attempted|bool
    - not postgres_docker_image_present

