---

- name: Set operating system information
  set_fact:
    is_rhel_centos_6: "{{ ((ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')) and (ansible_distribution_major_version == '6') }}"
    is_rhel7: "{{ (ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '7') }}"
    is_centos_7: "{{ (ansible_distribution == 'CentOS') and (ansible_distribution_major_version == '7') }}"
    is_rhel_centos_7: "{{ ((ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')) and (ansible_distribution_major_version == '7') }}"

- fail:
    msg: "This is not a supported system for installation. Must be RHEL 6/7, CentOS 6/7."
  when: not (is_rhel_centos_6 or is_rhel_centos_7)

- name: Get local package directory
  set_fact:
    pkg_install_dir: "{{ ansible_env['PKG_DIR'] | default(ansible_env['PWD'] + '/packages/') }}"
  when: pkg_install_dir is not defined

- name: Defaulting selinux_on to false
  set_fact:
    selinux_on: false

- name: Register selinux enabled command
  shell: selinuxenabled
  register: have_selinux_raw
  ignore_errors: yes

- name: Set selinux_on if selinux is enabled
  set_fact:
    selinux_on: true
  when:
    - have_selinux_raw.rc == 0

- name: Set qpc version (RHEL/CentOS 6)
  set_fact:
    qpc_package_name: "qpc.el6.noarch.rpm"
  when:
    - qpc_package_name is not defined
    - is_rhel_centos_6|bool

- name: Set qpc version (RHEL/CentOS 7)
  set_fact:
    qpc_package_name: "qpc.el7.noarch.rpm"
  when:
    - qpc_package_name is not defined
    - is_rhel_centos_7|bool

- name: Set qpc_rpm_local_path
  set_fact:
    qpc_rpm_local_path: "{{ pkg_install_dir }}{{ qpc_package_name }}"

- name: Set server_image_filename
  set_fact:
    server_image_filename: "quipucords_server_image.tar.gz"
  when:
    - server_image_filename is not defined

- name: Set server_image_local_path 
  set_fact:
    server_image_local_path: "{{ pkg_install_dir }}{{ server_image_filename }}"
  when:
    - server_image_local_path is not defined
  
- name: Set postgres_image_filename
  set_fact:
    postgres_image_filename: "postgres.{{ POSTGRES_VERSION }}.tar"
  when:
    - postgres_image_filename is not defined

- name: Set postgres_image_local_path
  set_fact:
    postgres_image_local_path: "{{ pkg_install_dir }}{{ postgres_image_filename }}"
  when:
    - postgres_image_local_path is not defined