---

- name: Test for presence of Docker
  shell: command -v docker
  register: have_docker_raw
  ignore_errors: yes

- name: Set variable state indicating presence of Docker
  set_fact:
    have_docker: "{{ have_docker_raw.rc == 0 }}"
