---

- name: Query GitHub for the latest release information
  uri:
    url: https://github.com/quipucords/quipucords/releases/latest/download/release_info.json
    validate_certs: no
    return_content: yes
  retries: 5
  delay: 5
  register: github_release_response
  until: github_release_response.status == 200 or github_release_response.status == 401
  changed_when: false
  when:
    - install_flag_server_version is not defined

- name: Load JSON release info
  set_fact:
    github_release_info: "{{ github_release_response.content | from_json }}"
  when:
    - install_flag_server_version is not defined
    - github_release_response is defined
    - github_release_response.content is defined

- name: Parse release version from github_release_info JSON
  set_fact:
    github_release: "{{ github_release_info.version }}"
  when:
    - install_flag_server_version is not defined
    - github_release_info is defined
    - github_release_info.version is defined

- name: Override default server_image_tag value with release value
  set_fact:
    server_image_tag: "{{ github_release }}"
  when:
    - install_flag_server_version is not defined
    - github_release is defined