---

- name: Check if user supplied server version when offline installation requested
  fail:
    msg: "server_version must be set when install_offline=true"
  when:
    - install_server|lower == 'true'
    - server_version is not defined

- name: Check if server version was set to empty string when offline installation requested
  fail:
    msg: "server_version is defined but is an empty string"
  when:
    - install_server|lower == 'true'
    - server_version is defined and server_version|length == 0

- name: Set QPC CLI RPM file path
  set_fact:
    qpc_rpm_local_path: "{{ pkg_install_dir }}{{ qpc_package_name }}"
  when: install_cli|lower == 'true'

- name: Check if QPC CLI RPM file exists
  stat:
    path: "{{ qpc_rpm_local_path }}"
  register: find_qpc_rpm_local
  when:
    - install_cli|lower == 'true'

- name: Fail if QPC CLI RPM is not present for offline installation
  fail:
    msg: "{{ qpc_rpm_local_path }} file not found and required for an offline installation"
  when:
    - install_cli|lower == 'true'
    - not find_qpc_rpm_local.stat.exists

- name: Set Quipucords server container image file name
  set_fact:
    server_image_filename: "quipucords_server_image.tar.gz"
  when:
    - server_image_filename is not defined

- name: Set Quipucords server container image file path
  set_fact:
    server_image_local_path: "{{ pkg_install_dir }}{{ server_image_filename }}"
  when:
    - server_image_local_path is not defined

- name: Check if Quipucords server container image file exists
  stat:
    path: "{{ server_image_local_path }}"
  register: find_server_image_local
  when:
    - install_server|lower == 'true'

- name: Fail if Quipucords server image file does not exist for offline installation
  fail:
    msg: "{{ server_image_local_path }} file not found and required for an offline installation"
  when:
    - install_server|lower == 'true'
    - not find_server_image_local.stat.exists

- name: Set PostgreSQL container image file name
  set_fact:
    postgres_image_filename: "postgres.{{ postgres_version }}.tar"
  when:
    - postgres_image_filename is not defined

- name: Set PostgreSQL container image file path
  set_fact:
    postgres_image_local_path: "{{ pkg_install_dir }}{{ postgres_image_filename }}"
  when:
    - postgres_image_local_path is not defined

- name: Check if local PostgreSQL container image exists
  stat:
    path: "{{ postgres_image_local_path }}"
  register: find_postgres_image_local
  when:
    - install_server|lower == 'true'

- name: Fail if PostgreSQL container image file does not exist for offline installation
  fail:
    msg: "{{ postgres_image_local_path }} file not found and required for an offline installation"
  when:
    - install_server|lower == 'true'
    - not find_postgres_image_local.stat.exists