---

- name: Start PostgreSQL container with Podman
  shell: "podman run --name {{ db_name }} -e POSTGRES_USER={{ db_user }} -e POSTGRES_PASSWORD='{{ db_password }}' -v qpc-data:/var/lib/postgresql/data -d {{db_image_name}}:{{postgres_version}}"
  become: true

- name: Waiting for PostgreSQL to spin up
  pause:
    seconds: 30
