---

- name: Set the Quipucords CLI RPM package name for RHEL/CentOS 6
  set_fact:
    qpc_package_name: "qpc.el6.noarch.rpm"
  when:
    - qpc_package_name is not defined
    - is_rhel_centos_6|bool

- name: Set the Quipucords CLI RPM package name for RHEL/CentOS 7
  set_fact:
    qpc_package_name: "qpc.el7.noarch.rpm"
  when:
    - qpc_package_name is not defined
    - is_rhel_centos_7|bool

- name: Set the Quipucords CLI RPM package name for RHEL8/CentOS 8
  set_fact:
    qpc_package_name: "qpc.el8.noarch.rpm"
  when:
    - qpc_package_name is not defined
    - is_rhel_centos_8|bool