---

- name: Check if PostgreSQL server docker container already running
  shell: "docker ps -a -f name='{{ db_name }}' | grep '{{ db_name }}'"
  become: true
  register: postgres_ps_raw
  ignore_errors: yes

- name: Remove running PostgreSQL container
  shell: "docker rm -f {{ db_name }}"
  become: true
  ignore_errors: yes
  when:
    - postgres_ps_raw['stdout_lines'] | length > 0

- name: Start PostgreSQL container with docker volume on RHEL 6 or CentOS 6
  shell: "docker run --name {{ db_name }}  -e POSTGRES_USER={{dbms_user}} -e POSTGRES_PASSWORD={{dbms_password}} -v /var/lib/docker/volumes/db-data:/var/lib/postgresql/data -d postgres:{{POSTGRES_VERSION}}"
  become: true
  when:
    - is_rhel_centos_6|bool

- name: Start PostgreSQL container with docker volume on RHEL 7 or CentOS 7
  shell: "docker run --name {{ db_name }}  -e POSTGRES_USER={{dbms_user}} -e POSTGRES_PASSWORD={{dbms_password}} -v db-data:/var/lib/postgresql/data -d postgres:{{POSTGRES_VERSION}}"
  become: true
  when:
    - is_rhel_centos_7|bool

- name: Waiting for PostgreSQL container to start up
  pause:
    seconds: 15