---

- name: Validate install_server is set to true or false
  fail:
    msg: "{{ install_server }} is invalid value for install_server.  Must be equal to true or false"
  when:
    - not install_server|lower == 'true'
    - not install_server|lower == 'false'

- name: Validate install_cli is set to true or false
  fail:
    msg: "{{ install_cli }} is invalid value for install_cli.  Must be equal to true or false"
  when:
    - not install_cli|lower == 'true'
    - not install_cli|lower == 'false'

- name: Validate install_offline is set to true or false
  fail:
    msg: "{{ install_offline }} is invalid value for install_offline.  Must be equal to true or false"
  when:
    - not install_offline|lower == 'true'
    - not install_offline|lower == 'false'

- name: Validate use_supervisord is set to true or false
  fail:
    msg: "{{ use_supervisord }} is invalid value for use_supervisord.  Must be equal to true or false"
  when:
    - not use_supervisord|lower == 'true'
    - not use_supervisord|lower == 'false'

- name: Validate open_port is set to true or false
  fail:
    msg: "{{ open_port }} is invalid value for open_port.  Must be equal to true or false"
  when:
    - not open_port|lower == 'true'
    - not open_port|lower == 'false'

- name: Gathering operating system information
  set_fact:
    is_rhel_centos_6: "{{ ((ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')) and (ansible_distribution_major_version == '6') }}"
    is_rhel7: "{{ (ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '7') }}"
    is_centos_7: "{{ (ansible_distribution == 'CentOS') and (ansible_distribution_major_version == '7') }}"
    is_rhel_centos_7: "{{ ((ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')) and (ansible_distribution_major_version == '7') }}"
    is_rhel8: "{{ (ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '8') }}"
    is_rhel_centos_8: "{{ ((ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')) and (ansible_distribution_major_version == '8') }}"

- name: Fail if running on machines other than RHEL 6/7/8 and CentOS 6/7
  fail:
    msg: "This is not a supported system for installation. Must be RHEL 6/7/8 or CentOS 6/7."
  when: not (is_rhel_centos_6 or is_rhel_centos_7 or is_rhel8)

- name: Set installer to use Docker for RHEL 6 and CentOS 6
  set_fact:
    use_docker: 'true'
  when:
    - is_rhel_centos_6|bool

- name: Set supervisord to true for RHEL 7/8 and CentOS 7
  set_fact:
    use_supervisord: 'true'
  when: is_rhel8 or is_rhel_centos_7

- name: Get local package directory
  set_fact:
    pkg_install_dir: "{{ ansible_env['PKG_DIR'] | default(ansible_env['PWD'] + '/packages/') }}"
  when: pkg_install_dir is not defined

- name: Defaulting SE Linux Quipucords server installation to false
  set_fact:
    selinux_on: false

- name: Determine if SE Linux is enabled
  shell: selinuxenabled
  register: have_selinux_raw
  ignore_errors: yes

- name: Set variable to use SE Linux sytax when SE Linux is enabled
  set_fact:
    selinux_on: true
  when:
    - have_selinux_raw.rc == 0

- name: Set QPC RPM package name for RHEL/CentOS 6
  set_fact:
    qpc_package_name: "qpc.el6.noarch.rpm"
  when:
    - qpc_package_name is not defined
    - is_rhel_centos_6|bool

- name: Set QPC RPM package name for RHEL/CentOS 7
  set_fact:
    qpc_package_name: "qpc.el7.noarch.rpm"
  when:
    - qpc_package_name is not defined
    - is_rhel_centos_7|bool

- name: Set QPC RPM package name for RHEL8/CentOS 8
  set_fact:
    qpc_package_name: "qpc.el8.noarch.rpm"
  when:
    - qpc_package_name is not defined
    - is_rhel_centos_8|bool

- name: Test for yum command
  shell: command -v yum
  register: have_yum_raw
  ignore_errors: yes

- name: Set variable to indicate if yum command was found
  set_fact:
    have_yum: "{{ have_yum_raw.rc == 0 }}"

- name: Set installation mode to use Docker if Quipucords server version is less than 0.9.1
  set_fact:
    use_docker: 'true'
  when:
  - server_version is defined
  - server_version < '0.9.1'
  - is_rhel_centos_7|bool

- name: Validate Quipucords server version compatibility with RHEL 8
  fail:
    msg: "Quipucords server {{ server_version }} cannot be installed on RHEL 8.  RHEL 8 requires version 0.9.1 or newer."
  when:
  - server_version is defined
  - server_version < '0.9.1'
  - is_rhel8|bool