---

- name: Validate install_server is set to true or false
  fail:
    msg: "{{ install_server }} is invalid value for install_server.  Must be equal to true or false"
  when:
    - not install_server|lower == 'true'
    - not install_server|lower == 'false'

- name: Validate install_cli is set to true or false
  fail:
    msg: "{{ install_cli }} is invalid value for install_cli.  Must be equal to true or false"
  when:
    - not install_cli|lower == 'true'
    - not install_cli|lower == 'false'
  
- name: Validate install_offline is set to true or false
  fail:
    msg: "{{ install_offline }} is invalid value for install_offline.  Must be equal to true or false"
  when:
    - not install_offline|lower == 'true'
    - not install_offline|lower == 'false'

- name: Validate use_supervisord is set to true or false
  fail:
    msg: "{{ use_supervisord }} is invalid value for use_supervisord.  Must be equal to true or false"
  when:
    - not use_supervisord|lower == 'true'
    - not use_supervisord|lower == 'false'

- name: Validate open_port is set to true or false
  fail:
    msg: "{{ open_port }} is invalid value for open_port.  Must be equal to true or false"
  when:
    - not open_port|lower == 'true'
    - not open_port|lower == 'false'

- name: Set operating system information
  set_fact:
    is_rhel_centos_6: "{{ ((ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')) and (ansible_distribution_major_version == '6') }}"
    is_rhel7: "{{ (ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '7') }}"
    is_centos_7: "{{ (ansible_distribution == 'CentOS') and (ansible_distribution_major_version == '7') }}"
    is_rhel_centos_7: "{{ ((ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')) and (ansible_distribution_major_version == '7') }}"
    is_rhel8: "{{ (ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '8') }}"
    is_rhel_centos_8: "{{ ((ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')) and (ansible_distribution_major_version == '8') }}"

- name: Fail if container_command is 'podman'
  fail:
    msg: "Podman is not supported yet. It is an upcoming update."
  when: container_command == 'podman'

- fail:
    msg: "This is not a supported system for installation. Must be RHEL 6/7 or CentOS 6/7."
  when: not (is_rhel_centos_6 or is_rhel_centos_7)

- name: Set container_command to podman if RHEL 8
  set_fact:
    container_command: "podman"
  when: is_rhel_centos_8|bool

- name: Get local package directory
  set_fact:
    pkg_install_dir: "{{ ansible_env['PKG_DIR'] | default(ansible_env['PWD'] + '/packages/') }}"
  when: pkg_install_dir is not defined

- name: Defaulting selinux_on to false
  set_fact:
    selinux_on: false

- name: Register selinux enabled command
  shell: selinuxenabled
  register: have_selinux_raw
  ignore_errors: yes

- name: Set selinux_on if selinux is enabled
  set_fact:
    selinux_on: true
  when:
    - have_selinux_raw.rc == 0

- name: Set qpc version (RHEL/CentOS 6)
  set_fact:
    qpc_package_name: "qpc.el6.noarch.rpm"
  when:
    - qpc_package_name is not defined
    - is_rhel_centos_6|bool

- name: Set qpc version (RHEL/CentOS 7)
  set_fact:
    qpc_package_name: "qpc.el7.noarch.rpm"
  when:
    - qpc_package_name is not defined
    - is_rhel_centos_7|bool
  
- name: Set install_flag_server_version to server_version
  set_fact:
    install_flag_server_version: "{{ server_version }}"
  when:
    - server_version is defined
  
- name: Test for yum command
  shell: command -v yum
  register: have_yum_raw
  ignore_errors: yes

- name: Set have_yum
  set_fact:
    have_yum: "{{ have_yum_raw.rc == 0 }}"