# Install playbook for Quipucords
---

- name: Install the Quipucords components
  hosts: localhost
  vars:
      install_server: 'true'
      install_cli: 'true'
      install_offline: 'false'
      use_supervisord: 'false'
      open_port: 'true'
      server_port: '9443'
      server_name: 'quipucords'
      postgres_version: '9.6.10'
      db_name: 'qpc-db'
      server_username: 'admin'
      server_password: 'qpcpassw0rd'
      server_user_email: 'admin@example.com'
      server_install_dir: "{{ansible_env['HOME'] + '/quipucords'}}"
      server_http_timeout: 120
      dbms_user: 'postgres'
      dbms_password: 'password'
      use_docker: 'false' # logic elsewhere will change this to docker for RHEL 6
      connect_job_timeout: 600
      inspect_job_timeout: 10800
      ansible_log_level: 0
      have_qpc_docker_containers: false
      have_qpc_podman_containers: false
  roles:
    - validate_common
    - role: validate_offline
      when:
        - install_offline|lower == 'true'
    - role: prep_common_docker
      when:
        - install_server | lower == 'true'
    - role: prep_common_podman
      when:
        - install_server | lower == 'true'
    - role: validate_podman
      when:
        - install_server | lower == 'true'
        - use_docker|lower == 'false'
    - role: uninstall_common_docker
      when:
        - install_server | lower == 'true'
        - have_docker
    - role: uninstall_common_podman
      when:
        - install_server | lower == 'true'
        - have_podman
    - role: install_docker_online
      when:
        - install_server|lower == 'true'
        - use_docker|lower == 'true'
    - role: start_docker_common
      when:
        - install_server|lower == 'true'
        - use_docker|lower == 'true'
    - role: install_postgres_offline_docker
      when:
        - install_offline|lower == 'true'
        - install_server|lower == 'true'
        - use_docker|lower == 'true'
    - role: install_postgres_offline_podman
      when:
        - install_offline|lower == 'true'
        - install_server|lower == 'true'
        - use_docker|lower == 'false'
    - role: start_postgres_common_docker
      when:
        - install_server|lower == 'true'
        - use_docker|lower == 'true'
    - role: prep_server_online
      when:
        - install_offline|lower == 'false'
        - install_server|lower == 'true'
    - role: prep_server_common_podman
      when:
        - install_server|lower == 'true'
        - use_docker|lower == 'false'
    - role: prep_server_common_docker
      when:
        - install_server|lower == 'true'
        - use_docker|lower == 'true'
    - role: install_server_online
      when:
        - install_offline|lower == 'false'
        - install_server|lower == 'true'
    - role: start_server_common_docker
      when:
        - install_server|lower == 'true'
        - use_docker|lower == 'true'
    - role: start_server_common_podman
      when:
        - install_server|lower == 'true'
        - use_docker|lower == 'false'
    - role: start_postgres_common_podman
      when:
        - install_server|lower == 'true'
        - use_docker|lower == 'false'
    - role: migrate_docker_data_to_podman
      when:
        - install_server|lower == 'true'
        - have_qpc_docker_containers
        - not have_qpc_podman_containers
        - use_docker|lower == 'false'
    - role: install_cli_offline
      when:
        - install_cli|lower == 'true'
        - install_offline|lower == 'true'
    - role: install_cli_online
      when:
        - install_cli|lower == 'true'
        - install_offline|lower == 'false'
    - role: config_cli_common
      when:
        - install_cli|lower == 'true'
    - role: validate_cli_install
      when:
        - install_cli|lower == 'true'
    - role: validate_server_install
      when:
        - install_server|lower == 'true'
