# Install playbook for Quipucords
---

- name: Install the Quipucords components
  hosts: localhost
  vars:
      install_server: 'true'
      install_cli: 'true'
      install_offline: 'false'
      use_supervisord: 'false'
      open_port: 'true'
      server_port: '9443'
      server_name: 'quipucords'
      container_command: 'docker'
      server_http_timeout: 120
      dbms_user: 'postgres'
      dbms_password: 'password'
      connect_job_timeout: 600
      inspect_job_timeout: 10800
      ansible_log_level: 0
  roles:
    - validate_common
    - role: validate_offline
      when: install_offline|lower == 'true'
    - role: install_docker_online
      when:
        - install_server|lower == 'true'
        - container_command|lower == 'docker'
    - role: start_docker_common
      when:
        - install_server|lower == 'true'
        - container_command|lower == 'docker'
    - role: install_postgres_offline
      when:
        - install_offline|lower == 'true'
        - install_server|lower == 'true'
    - role: start_postgres_common
      when: install_server|lower == 'true'
    - role: prep_server_online
      when:
        - install_offline|lower == 'false'
        - install_server|lower == 'true'
    - role: prep_server_common
      when: install_server|lower == 'true'
    - role: install_server_online
      when:
        - install_offline|lower == 'false'
        - install_server|lower == 'true'
    - role: start_server_common
      when: install_server|lower == 'true'
    - role: install_cli_offline
      when:
        - install_cli|lower == 'true'
        - install_offline|lower == 'true'
    - role: install_cli_online
      when:
        - install_cli|lower == 'true'
        - install_offline|lower == 'false'
    - role: config_cli_common
      when: install_cli|lower == 'true'
    - role: validate_cli_install
      when: install_cli|lower == 'true'
    - role: validate_server_install
      when: install_server|lower == 'true'
