# Install playbook for Quipucords
---

- name: Install the Quipucords components
  hosts: localhost
  roles:
    - prep
    - epel
    - role: docker
      when: install_server | bool
    - role: qpc_server
      when: install_server | bool
    - role: qpc_cli
      when: install_cli | bool
    - role: validate_install
      when: install_server | bool

