# Install playbook for Quipucords
---

- name: Install the Quipucords components
  hosts: localhost
  vars:
      install_server: 'true'
      install_cli: 'true'
      install_offline: 'false'
      use_supervisord: 'false'
      open_port: 'true'
      server_port: '9443'
      server_name: 'quipucords'
      server_http_timeout: 120
      dbms_user: 'postgres'
      dbms_password: 'password'
      connect_job_timeout: 600
      inspect_job_timeout: 10800
      ansible_log_level: 0
  roles:
    - param_validation
    - install_prep
    - role: param_validation_offline
      when: install_offline|lower == 'true'
    - role: install_epel_online
      when: install_offline|lower == 'false'
    - role: docker
      when: install_server|lower == 'true'
    - role: postgres_offline
      when: install_offline|lower == 'true'
    - postgres
    - role: qpc_server
      when: install_server|lower == 'true'
    - role: qpc_cli
      when: install_cli|lower == 'true'
    - role: validate_install
      when: install_server|lower == 'true'
