---

- name: Rename Quipucords server {{ container_command }} image to version specific cache name
  command: cp "{{ pkg_install_dir }}{{ github_server_filename }}" "{{ qpc_server_version_filename }}"
  when:
    - not quipucords_docker_image_present

- name: Default that {{ container_command }} load was not attempted for Quipucords server
  set_fact:
    load_quipucords_docker_server_attempted: false

- name: "{{ container_command }} load was attempted for Quipucords server"
  set_fact:
    load_quipucords_docker_server_attempted: true
  when:
    - not quipucords_docker_image_present

- name: Load Quipucords image into local {{ container_command }} registry
  shell: "{{ container_command }} load -i {{ qpc_server_version_filename }}"
  become: true
  when:
    - not quipucords_docker_image_present

- name: Check for Quipucords server {{ container_command }} image presence
  shell: "{{ container_command }} images | grep {{ server_docker_image_name }} | grep {{ server_image_tag }}"
  become: true
  register: quipucords_docker_image_raw
  ignore_errors: yes
  when:
    load_quipucords_docker_server_attempted|bool

- name: Set Quipucords {{ container_command }} image presence to false
  set_fact:
    quipucords_docker_image_present: false
  when:
    - load_quipucords_docker_server_attempted|bool
    - quipucords_docker_image_raw.rc != 0

- name: Set Quipucords {{ container_command }} image presence to true if output is not empty
  set_fact:
    quipucords_docker_image_present: "{{ quipucords_docker_image_raw['stdout_lines']|length > 0 }}"
  when:
    - load_quipucords_docker_server_attempted|bool
    - quipucords_docker_image_raw.rc == 0
    - "'stdout_lines' in quipucords_docker_image_raw"

- name: Make sure Quipucords server {{ container_command }} image loaded (it successfully loaded if skipped)
  fail:
    msg: "The Quipucord server's {{ container_command }} image was not found in the output of the {{ container_command }} images command."
  when:
    - load_quipucords_docker_server_attempted|bool
    - not quipucords_docker_image_present

- name: Check for QPC server is already running
  shell: "{{ container_command }} ps -a -f name={{ server_name }} | grep {{server_name}}"
  become: true
  register: qpc_ps_raw
  ignore_errors: yes

- name: Remove running QPC server container
  shell: "{{ container_command }} rm -f {{server_name}}"
  become: true
  ignore_errors: yes
  when:
    - qpc_ps_raw['stdout_lines'] | length > 0

- name: Start Quipucords server linked to Postgres {{ container_command }} container
  shell: "{{ container_command }} run --name {{ server_name }} --link {{ db_name }}:qpc-link -d -e USE_SUPERVISORD={{ use_supervisord }} -e QPC_SERVER_TIMEOUT={{ server_http_timeout }} -e QPC_DBMS_USER={{ dbms_user }} -e QPC_DBMS_PASSWORD={{ dbms_password }} -e QPC_DBMS_HOST='qpc-db' -e ANSIBLE_LOG_LEVEL={{ ansible_log_level }} -e NETWORK_CONNECT_JOB_TIMEOUT={{ connect_job_timeout }} -e NETWORK_INSPECT_JOB_TIMEOUT={{ inspect_job_timeout }} -e QPC_SERVER_USERNAME={{ server_username }} -e QPC_SERVER_USER_EMAIL={{ server_user_email }} -e QPC_SERVER_PASSWORD={{ server_password }} -p {{ server_port }}:443 -v {{ server_install_dir }}/sshkeys:/sshkeys{{ dir_mount_selinux }} -v {{ server_install_dir }}/data:/var/data{{ dir_mount_selinux }} -v {{ server_install_dir }}/log:/var/log{{ dir_mount_selinux }} -i {{ server_image_and_tag }}"
  become: true
  when: container_command == 'docker'

# With podman we have to set the host to localhost instead of qpc-db, because podman does not create a proxy like docker does
- name: Start Quipucords server {{ container_command }} container (RHEL 8)
  shell: "{{ container_command }} run --name {{ server_name }} -p {{ server_port }}:443 -d -e USE_SUPERVISORD={{ use_supervisord }} -e QPC_SERVER_TIMEOUT={{ server_http_timeout }} -e QPC_DBMS_USER={{ dbms_user }} -e QPC_DBMS_PASSWORD={{ dbms_password }} -e ANSIBLE_LOG_LEVEL={{ ansible_log_level }} -e NETWORK_CONNECT_JOB_TIMEOUT={{ connect_job_timeout }} -e NETWORK_INSPECT_JOB_TIMEOUT={{ inspect_job_timeout }} -e QPC_SERVER_USERNAME={{ server_username }} -e QPC_SERVER_USER_EMAIL={{ server_user_email }} -e QPC_SERVER_PASSWORD={{ server_password }} -v {{ server_install_dir }}/sshkeys:/sshkeys{{ dir_mount_selinux }} -v {{ server_install_dir }}/data:/var/data{{ dir_mount_selinux }} -v {{ server_install_dir }}/log:/var/log{{ dir_mount_selinux }} {{ server_image_and_tag }}"
  become: true
  ignore_errors: yes
  when: container_command == 'podman'

- name: Start Postgres container with {{ container_command }} volume (RHEL 8/Podman)
  shell: "{{ container_command }} run --name {{ db_name }} --network=container:{{ server_name }} -e POSTGRES_USER={{dbms_user}} -e POSTGRES_PASSWORD={{dbms_password}} -v db-data:/var/lib/postgresql/data -d postgres:{{POSTGRES_VERSION}}"
  become: true
  when: container_command == 'podman'

- name: Waiting for Postgres to spin up
  pause:
    seconds: 30
  when: container_command == 'podman'

- name: Restart the Quipucords server container (RHEL 8/Podman)
  shell: "{{ container_command }} restart {{ server_name }}"
  become: true
  when: container_command == 'podman'

