---

- name: Test for yum command
  shell: command -v yum
  register: have_yum_raw
  ignore_errors: yes

- name: Set have_yum
  set_fact:
    have_yum: "{{ have_yum_raw.rc == 0 }}"

- name: Test for rpm command
  shell: command -v rpm
  register: have_rpm_raw
  ignore_errors: yes

- name: Set have_rpm
  set_fact:
    have_rpm: "{{ have_rpm_raw.rc == 0 }}"

- name: Check for EPEL rpm (RHEL/Centos)
  yum:
    name: epel-release
    state: installed
  register: have_epel_rpm_raw
  become: true
  ignore_errors: yes
  when:
    - have_rpm|bool

- name: Set have_epel_rpm (RHEL/Centos)
  set_fact:
    have_epel_rpm: "{{ 'epel-release is already installed' in have_epel_rpm_raw['results'][0] }}"
  when:
    - "'results' in have_epel_rpm_raw"

- name: Default have_epel_rpm (RHEL/Centos)
  set_fact:
    have_epel_rpm: false
  when:
    - have_epel_rpm is not defined

- name: Find installable local epel rpm (RHEL/Centos)
  find:
    paths: "{{ pkg_install_dir }}"
    patterns: 'epel*.rpm'
  register: find_epel_rpm_local_raw
  when:
    - not have_epel_rpm

- name: Set find_epel_rpm_local (RHEL/Centos)
  set_fact:
    find_epel_rpm_local: "{{ find_epel_rpm_local_raw['matched'] == 1 }}"
  when:
    - find_epel_rpm_local_raw is defined
    - "'matched' in find_epel_rpm_local_raw"

- name: Set find_epel_rpm_local_path (RHEL/Centos)
  set_fact:
    find_epel_rpm_local_path: "{{ find_epel_rpm_local_raw['files'][0]['path'] }}"
  when:
    - find_epel_rpm_local is defined
    - find_epel_rpm_local|bool

- name: Install EPEL from local path (RHEL/Centos)
  shell: rpm -Uvh --force "{{find_epel_rpm_local_path}}"
  become: true
  when:
    - not have_epel_rpm
    - find_epel_rpm_local|bool

- name: Install EPEL for RHEL 6 from internet (RHEL/Centos 6)
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
    state: present
  become: true
  when:
    - is_rhel_centos_6|bool
    - not have_epel_rpm
    - not find_epel_rpm_local

- name: Install EPEL for RHEL 7 from internet (RHEL/Centos 7)
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  become: true
  when:
    - is_rhel_centos_7|bool
    - not have_epel_rpm
    - not find_epel_rpm_local
